### ISSUE TITLE
[Nice to have] User-friendly error messages

### ISSUE THREAD

**Issue by krlv** [kelunik/gateway#10]
Currently, if something goes wrong in the Gateway internals, user will see the full stack trace of error instead of short message (which is good for active development, but, probably, should be fixed in the future).

Small comparison of how Gateway, Symfony and PHP built-in servers handle socket exception (address already in use):

Gateway output:
```shell
PHP Fatal error:  Uncaught Amp\Socket\SocketException: Could not create server 127.0.0.1:8000: [Error: #0] Address already in use in /Users/eugene/Projects/gateway/vendor/amphp/socket/src/functions.php:56
Stack trace:
#0 /Users/eugene/Projects/gateway/bin/gateway(69): Amp\Socket\listen('127.0.0.1:8000')
#1 [internal function]: {closure}('a', NULL)
#2 /Users/eugene/Projects/gateway/vendor/amphp/amp/lib/Coroutine.php(41): Generator->current()
#3 /Users/eugene/Projects/gateway/vendor/amphp/amp/lib/Loop/Driver.php(123): Amp\Coroutine->__construct(Object(Generator))
#4 /Users/eugene/Projects/gateway/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#5 /Users/eugene/Projects/gateway/vendor/amphp/amp/lib/Loop.php(84): Amp\Loop\Driver->run()
#6 /Users/eugene/Projects/gateway/bin/gateway(112): Amp\Loop::run(Object(Closure))
#7 {main}
  thrown in /Users/eugene/Projects/gateway/vendor/amphp/socket/src/functions.php on line 56

Fatal error: Uncaught Amp\Socket\SocketException: Could not create server 127.0.0.1:8000: [Error: #0] Address already in use in /Users/eugene/Projects/gateway/vendor/amphp/socket/src/functions.php:56
Stack trace:
#0 /Users/eugene/Projects/gateway/bin/gateway(69): Amp\Socket\listen('127.0.0.1:8000')
#1 [internal function]: {closure}('a', NULL)
#2 /Users/eugene/Projects/gateway/vendor/amphp/amp/lib/Coroutine.php(41): Generator->current()
#3 /Users/eugene/Projects/gateway/vendor/amphp/amp/lib/Loop/Driver.php(123): Amp\Coroutine->__construct(Object(Generator))
#4 /Users/eugene/Projects/gateway/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#5 /Users/eugene/Projects/gateway/vendor/amphp/amp/lib/Loop.php(84): Amp\Loop\Driver->run()
#6 /Users/eugene/Projects/gateway/bin/gateway(112): Amp\Loop::run(Object(Closure))
#7 {main}
  thrown in /Users/eugene/Projects/gateway/vendor/amphp/socket/src/functions.php on line 56
```

Symfony output (in color):
```
[Thu Dec 20 00:43:00 2018] Failed to listen on 127.0.0.1:8000 (reason: Address already in use)

[ERROR] Server terminated unexpectedly.
```

PHP built-in server output:
```
[Thu Dec 20 01:59:26 2018] Failed to listen on 127.0.0.1:8000 (reason: Address already in use)
```

**Comment by kelunik** [comment]
Thanks! This one is fixed now, other issues will be dealt with case-by-case.
